### PR TITLE
Remove file extensions to load as modules

### PR DESCRIPTION
**Pull request by AStoker**
Removed the file extensions from the `require` calls so that files are
loaded up correctly as modules and don’t lose their module path.

Resolves: https://github.com/arjunmehta/heartbeats/issues/6

### CODE REVIEW

**Comment by arjunmehta** [comment]
@AStoker Nice, I appreciate this. Been a long time since I've used file extensions in my require statements. :D

I'll merge this shortly and we can push a new version as early as tomorrow.

**Comment by AStoker** [comment]
Awesome, thanks :)

**Comment by AStoker** [comment]
Might be worth addressing this too when you publish (https://github.com/arjunmehta/heartbeats/issues/5), if it hasn't been already.

**Comment by arjunmehta** [comment]
@AStoker Published v3.1.4 with your fix. Thank you so much!

**Comment by AStoker** [comment]
Thank you!

**Comment by stephenhuey** [comment]
Thanks!

**Pull request merged**
